# This is a basic workflow to help you get started with Actions

name: Code quality

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install

      - run: yarn lint

      - uses: getsentry/action-git-diff-suggestions@main
        with:
          message: eslint

      - run: yarn test
