version: "3.9"
services:
  web:
    container_name: web.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ExchangeSettings__ApiKey=9dnZa2uPwZk5igO0NaKtEjrxfacIYX8vmWGcdTbkPxLE0b4LzdpQfT9viq74wHzx
      - ExchangeSettings__ApiSecret=vRJcVeH0NUoDnaWzSj3NjVVg5nwukGsetAKW0PS7gzI749WmBWcKDoYB301uoDEN
    image: local:backend
    build: ./
    ports:
      - "5000:80"
    networks:
      - elastic
    depends_on:
      - elasticsearch
  
  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   ports:
    - 9200:9200
  #  volumes:
    # - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   networks:
    - elastic

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.9.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
   networks:
    - elastic
  
networks:
  elastic:
    driver: bridge

# volumes:
  # elasticsearch-data: